### ISSUE TITLE
insertInto(tableName:values:error:) throws build error

### ISSUE THREAD

**Issue by tyczj** [nerdyc/Squeal#34]
when I try to use `insertInto(tableName:values:error:)` xcode throws an error saying `Missing argument for parameter 'columns' in call`

If I use `db?.insertInto(tableName, columns:, values:, error: err)` it builds fine

**Comment by nerdyc** [comment]
Can you provide more detail about how you're calling this method?

There are two insertInto(...) methods. One takes two arrays, and the other takes a dictionary. The problem you're having is that the compiler thinks that you're trying to call the array-based one -- insertInto(tableName:columns:values:error:) -- when you are actually trying to call the dictionary one -- insertInto(tableName:values:error:) 

I would double check the types of the variables you're passing in.

**Comment by tyczj** [comment]
I dont have exactly how I was doing it before but it was something along the lines of

    insertInto("tableName":["key":value,     "key":value]:error:)

and it gave me the error.

i basically just followed the insert example you have in the ReadMe

**Comment by alantheprice** [comment]
I have run into the same thing, in my case it was a type issue with the error rather than the rest of the function parameters. 
The error parameter I was trying to pass in was : `var error:NSError? = nil`
when I should have been passing in an error pointer like `var error:NSErrorPointer = nil`

Once I fixed this, I was good to go, hopefully that helps.
